### ISSUE TITLE
4.2.4 bug fixes about sound

### ISSUE THREAD

**Issue by xnum** [haha01haha01/HaSuite#2]
Hi,
I traced some threads[1][2] to solve sound change issue in sound.wz,
and I found that some bugs be fixed from version 4.2.3 -> 4.2.4.

I want to write a program that replace sounds automatically,
but I'm not sure what part of codes fixed this bug,
I tried to look up commit logs but only writes 'bug fix' and 'bug fix' ...
can you help me to figure out this bug.

thanks

[1] http://forum.ragezone.com/f701/release-universal-harepacker-version-892005/
[2] http://forum.ragezone.com/f701/v0-62-sound-wz-skill-1060923/

**Comment by hadeutscher** [comment]
Hi,
You can look at the commit history of a specific file. If you look at the history of WzSoundProperty.cs (in project MapleLib2), you will see that the relevant commit is https://github.com/haha01haha01/MapleLib/commit/4bb9f3edf69fa7737f26f4b8f4f472f5c929db85

However, it is recommended that you just use the latest version and it will probably work.

-haha01haha01
