### ISSUE TITLE
[Enhancement] Flac file export

### ISSUE THREAD

**Issue by PratikBhusal** [haha01haha01/HaSuite#4]
I was wondering if there was any way to directly extract and export the music into a lossless format (eg: .flac) for archival purposes. I probably do not have the qualifications to do much, but if necessary I can do my best to contribute as much as i can.

**Comment by icelemon1314** [comment]
first you can dump the music file,and then use other software convert to flac format.

**Comment by fenying** [comment]
Actually I think it makes no sense, becuase the music insides .wz files is not lossless.

**Comment by Kagamia** [comment]
Almost all of the sounds are stored as `mp3` format, but `mp3` is lossy. The conversion is meaningless.

Others are PCM/WAV for sound effects but I think u wont need them :)

**Comment by PratikBhusal** [comment]
@fenying if most of the music already inside the .wz files are not lossless, wouldn't exporting as a `mp3` further reduce the audio quality?

**Comment by Kagamia** [comment]
@PratikBhusal Exporting is simply a file-bytes-copy function, it wouldn't have any compress/decompress/resampling/codec functions.

**Comment by PratikBhusal** [comment]
Ah okay. Thank you for the information! I will close this then.
